export const ACHIEVEMENTS = [
  { id: "first_game", title: "Primera partida", description: "Completa tu primera partida", icon: "🎮", xpReward: 50 },
  { id: "perfect_game", title: "Perfección", description: "Responde 10/10 en una partida", icon: "💯", xpReward: 100 },
  { id: "streak_3", title: "Racha inicial", description: "3 días seguidos jugando", icon: "🔥", xpReward: 75 },
  { id: "streak_7", title: "Una semana", description: "7 días seguidos", icon: "🔥🔥", xpReward: 150 },
  { id: "streak_30", title: "Un mes", description: "30 días seguidos", icon: "🏅", xpReward: 500 },
  { id: "combo_5", title: "5 en racha", description: "5 respuestas correctas seguidas", icon: "⚡", xpReward: 50 },
  { id: "combo_10", title: "Imparable", description: "10 respuestas correctas seguidas", icon: "⚡⚡", xpReward: 150 },
  { id: "level_10", title: "Nivel 10", description: "Alcanza el nivel 10", icon: "⭐", xpReward: 200 },
  { id: "level_50", title: "Nivel 50", description: "Alcanza el nivel 50", icon: "🌟", xpReward: 500 },
  { id: "level_100", title: "Maestro", description: "Alcanza el nivel 100", icon: "👑", xpReward: 1000 },
  { id: "games_10", title: "10 partidas", description: "Juega 10 partidas", icon: "🎯", xpReward: 100 },
  { id: "games_100", title: "100 partidas", description: "Juega 100 partidas", icon: "🏆", xpReward: 300 },
  { id: "death_survive", title: "Superviviente", description: "Llega a 15 preguntas en muerte súbita", icon: "💀", xpReward: 150 },
  { id: "duel_first", title: "Primer duelo", description: "Completa tu primer duelo", icon: "⚔️", xpReward: 75 },
  { id: "duel_winner", title: "Ganador nato", description: "Gana 5 duelos", icon: "🥇", xpReward: 200 },
  { id: "cie_master", title: "Experto CIE", description: "Responde 50 preguntas CIE correctamente", icon: "📋", xpReward: 200 },
  { id: "ranking_top10", title: "Top 10", description: "Entra al top 10 del ranking semanal", icon: "📊", xpReward: 250 },
  { id: "ranking_top1", title: "Número 1", description: "Llega al #1 del ranking semanal", icon: "👑", xpReward: 500 },
  { id: "share_result", title: "Presume tu score", description: "Comparte tu primer resultado", icon: "📤", xpReward: 30 },
  { id: "premium", title: "Supporter", description: "Adquiere la versión premium", icon: "💎", xpReward: 100 },
];
